[project]
name = "glasses-overlay"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "requests",
    "fastapi",
    "uvicorn[standard]",
    "pydantic",
    "replicate"
]

[dependency-groups]
dev = ["pytest>=8.4.1"]